language: java
jdk:
- oraclejdk8
- oraclejdk7
addons:
  sonarqube: true
env:
  global:
  - secure: SONAR_TOKEN=Hk2BrZUW8GOPnGU0Wd6EqZWSkTAikxjZObk/UFthzh0zDdh5B9tGi2lT5iG7Nr2T2JHEUyzQQhmDAktdJEsy3ahBt/XDB/ifmoURzAReU2VF/HT8Eb6u+v3YTK4wioLM65sUokzqVU2258/h1EMpY9OeMcpF5fS1R1vYP36e68tfBsuhJ1BidKV1ZUZdn/WJ1q+TMW6zoSJ8zjMdPGIwnoICNLZL5PnJbPWIaQouGZZtCD5h/97ACPDmqnkY0ysIDFgPbpDP8UxkKm/5WC8SBAJuG/jQFx6nMCvwdPVuX1PLbyDFGafIBwo/pQt99Y5Gk2vHI6qHvTj4fJFQWRzVCOc5+Q5iB2x2rEs4/Tb8klDXPePF/O8nSe4TtKco85DtDPA1QGztVw25fmmXqRS5mIeNtx11CAYBLreKSGQ4TTL2l/89cJHx7G/6gB05A83ynbnrWNASkXfGaugLsNNWiimMiLims6MkTwJPLN1kRSnZCgWPKOaAsFHpLt+E2uHhdrviQwh6le4EnK2O+1Id4KWK8AtlOA+cLyxDhVS18meKucpmvH/siGmRxF/pDOiPqp0qlM4xRmLrTSY4YxJju9N7UoukjuWVbc913Z2mYMhjE+wr8zidAGgIzCOVDuTBOSNMWtTcLZWzI2fjbAuGbpD4xYckQDmmsZIN/4Rvy9w=
script: gradle clean build
after_success:
- gradle cobertura coveralls
- sonar-scanner -Dsonar.login=$SONAR_TOKEN
notifications:
  email: false
  slack:
    rooms:
      - secure: HATwuj9Ki2Q41w2OEbjlaRBpcvCvyC90NSuXQhEXD07O9jwDcOIvayoUf4lCBu1m6cHUg6Bm4K8tLunOUEXKjJf6h4hiRfJW7MJ+jDnT8jMQ4ZPi2PuAHJ02m4NC9vckHIleseDJBOHCDMpqa89j9H4lKWNNXjZV0j29+WhrQZ9ntPM7RJWDet6uRFSTez/neGTknd5WTT52QP+7j+tVIJWFn0Zzpvq2HYHHlZr97GZF5O8Iw7sfIolAPhPUMn308LjC4vwmt55mavuvEYQP/RbACwaHgcBmkFMJ6ALdYHFUzI8qRA57Q/nMqx0A03TslJNn/aYfw/jzJd4lqeD6TQH/8MM+wr3UqDmoEfQAdBmluuVb60doRo3++iyjWCaErh3JSb7yMNYqosTLvhHt6VZ+hG0gpUE5FMXRg1461xGrX1vlT8NtP2OGgGa11CKB4dH6Xs6hbuVSQUnye73L+/NI7httqnHI1kaogzGWh1P0m1jxB+nw+BtJOjjSawuIIpiWo1oQmcBoh3eTQM2T65x2k4W0ggecRJgu2rWEUcnBcGJ008ikqjX3lti9/XsxDrWiJmnC+Fr/zcJXocOefKoDIIFN9Me2YufBmAZIiVh0I1imd3cG2SPOhsBLdKrLog851YQ1HefjtAB0smT3MHynICv37DeyJFp/mC7qSQM=
    on_success: always
    on_failure: always
  pushover:
    api_key:
      secure: iWtRTp919xSg5ENtoqN71v4ekbpaR9dukbh5gCPd4hqxXJCZk4hN+Kd3f8ZmhRc4UGTp7Iu8JD2VlX1bhrCrKffnQrWmCSLAcLmUKqdKP0nozTG1J7IrZV/7rMGEo99zP4ybBlu7JV1N4dcJqBfOKBJ1/JgWI+lHIusUr6wtDgmkvDhdGJ750JWFPxve5p2KPbib061gBAaWMLX6Ur4On49Wxke3tlfs3cgdcZlwriYeiEhwXTP+woS3g8hh4f3ZHMC72dmDJg7CFTfNeNbZb0EOphnxdxEcc6TmjVWs/5IPzkbojr7wHMZFie6SI1Iq/nd13y7I/lEKb/4I8vq1pLVtqnr0L7D/zUTm71xvO/eTR+RqbjZtqrtslH0wKySWeFuFkk6hz1xFsZ6FFwt12u6xicbfBCESHr9HZ2HTNpRX9S4S48QW58BZu4RkxBZVtNfHhS8+6IV3Vc484udpcsE/I1V01R/RMtJ4xtsrVxZW3sWmkyO54OnCFvjUOF5ZqFvT6NxeexfHwfOhsOKjD8ZG+T7Zlv+HYT8M7VokKDdPkjCIT+xXd5zBdJEEg5+Q3xoQfrGnENj09GhdzKwWAgxCJCR/VoBZwk70nO1iUsPZJzVYm+mgGaTB2orbtCNL/2EwW39GbwstO38yRpq9fIwH2Fd69VHpMB8Mx6qU4EM=
    users:
      - secure: K+Go/nftkZZXVzKEyomP0ZZbhGM3nPkgti39nqHGm1DYJMLsGr3bFP5yiZylN3qZ5gFral8GWsW7SntbI9XGrBDk8J7B5ZBhTfozCwzU7/Ukz3aDJbYH38ZWszHWEKyLPaoBEUCKvWL3Rsx4fPwiP23LPmt5xuO4TOWbodNze4tK5MO6m+9gnhVsRTvqQpJ2ALIZeh9SeqXAE8TsCTBkdCL1LSuAf8IFwsNa+Qz0cva2a3CxDaQhf2QbCRFIxc9e6QhiyZzhcYi4KQ4hIfSu+lhn6DMSZ0nc1fULhhCbEGnOLj4blV5G9xIX437Krq4HjA4iYT3sko5nw/4obFhk/qF1kRiS5SFEJBGAWXha9T3Kl7XXxMLhCz7ZHd5Scxz6mcTB67NdhDhvKBirAttTbcQrD2zNPN59UbReeW+J6lui0Wy84+lw4CasLQkQ+/trcWYmHC2EF+cvXAiVCYvtt3y54LUPJNF0AqqwBUwiKxic2X4GNHvNUIDEf1io1+2/Muec2N8iZFvfTvYmFm6vVUO9h+QdRPaKr4jgZmHgHNv9p3HoPzC+BQnI3yhlbNJMIDv01MpKjXudUym6IVUKWWeCnSO4cjxkQ1qfpzpopoywt8eWhDRxHNK0Box2axhhIUZOfra5Q69CN7qOALHILHJN+ylZnbSQtSN3EKT++28=
    on_success: always
    on_failure: always
