codecov:
  notify:
    require_ci_to_pass: true
comment:
  behavior: default
  layout: header, diff
  require_changes: false
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: true
    project: true
  notify:
    slack:
      default:
          url: "https://hooks.slack.com/services/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"
          threshold: 10%
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
